### ISSUE TITLE
Changing options doesn't change editor

### ISSUE THREAD

**Issue by matthellstrom** [marucjmar/ember-cli-tinymce#10]
When I change an option in my js, it doesn't update the editor. For instance:

this.set('tinymceOpts.resize', 'both');

doesn't change the editor to be resizable. I also tried changing the width, same result.

Property is set up as follows:

	tinymceOpts: {
		height: 300,
		width: 600,
		resize: false,
	    selector: "textarea",
	    plugins: [
	        "advlist autolink lists link image charmap print preview anchor",
	        "searchreplace visualblocks code fullscreen",
	        "insertdatetime media table contextmenu paste textcolor"
	    ],
	    toolbar: "insertfile undo redo | styleselect | bold italic | forecolor backcolor | alignleft               aligncenter alignright alignjustify | bullist numlist outdent indent | link image",
		content_css: '/assets/css/bootstrap.min.css'			
	},

My html reads:

{{tinymce-editor options=tinymceOpts value=htmlText onValueChanged=(action "htmlChanged")}}

Do I need to do something else to make the editor change?

**Comment by marucjmar** [comment]
Hi,

Ember observer could not observe dynamic keys of object.

Try this example
```
triggerOptions(){
  this.set('tinymceOpts', {});
  Ember.run.later(() =>{
   this.set('tinymceOpts.resize', 'both');
 },100)
}
```

**Comment by matthellstrom** [comment]
This wipes out all my previous settings, and doesn't change the one I need to change. I also get this in my console:

Uncaught TypeError: Cannot read property 'cloneNode' of null
    at Object.serialize (tinymce.min.js:5)
    at B.getContent (tinymce.min.js:11)
    at Class.contentChanged (tinymce-editor.js:30)
    at Backburner.run (ember.debug.js:678)
    at ember.debug.js:980

**Comment by marucjmar** [comment]
So you can write this code:

```
triggerOptions(){
      let currentOptions = this.get('tinymceOpts');
      this.set('tinymceOpts', {});
      Ember.run.later(() =>{
       currentOptions.resize = false
       this.set('tinymceOpts', currentOptions);
      },100)}
```

**Comment by matthellstrom** [comment]
That works perfectly! Thanks!

**Comment by matthellstrom** [comment]
Probably shouldn't have closed. It works, but still getting the cloneNode error

**Comment by marucjmar** [comment]
Ok fix this. Update package to version 0.1.6, Thanks

**Comment by matthellstrom** [comment]
OK thanks!

**Comment by abhikapuria** [comment]
I am facing a similar issue however while I was going through this thread I was wondering where do I need to place triggerOptions function

**Comment by abhikapuria** [comment]
Hi, I am using 0.1.6 version but still I getting,
Uncaught TypeError: Cannot read property 'cloneNode' of null
