### ISSUE TITLE
Uncaught TypeError: Cannot read property 'body' of null

### ISSUE THREAD

**Issue by bluscreen** [marucjmar/ember-cli-tinymce#11]
I put the extension into a component using v. 0.1.6 and Ember v2.11
When I call the save action from the controller, a content changed event is fired, even though probably the editor has been destroyed already, causing this exception to rise:

```
Uncaught TypeError: Cannot read property 'body' of null
    at B.getBody (tinymce.min.js:11)
    at B.getContent (tinymce.min.js:11)
    at Class.contentChanged (tinymce-editor.js:30)
    at Backburner.run (ember.debug.js:718)
    at ember.debug.js:1018
```

Here is the cause:
```
        // Call onValueChanged if editor content changes
        contentChanged: function contentChanged(editor) {
                this.onValueChanged(editor.getContent());
        },
```

There would need to be some possiblity to deregister the component before saving.. does anyone know how this could be achieved in a simple way?
Best regards,

Daniel

**Comment by marucjmar** [comment]
You can show the controller action?
