### ISSUE TITLE
Uncaught TypeError: Cannot read property 'cloneNode' of null

### ISSUE THREAD

**Issue by abhikapuria** [marucjmar/ember-cli-tinymce#13]
Hi,

I am getting this error,
**Uncaught TypeError: Cannot read property 'cloneNode' of null**
whenever I try to type anything in the text editor also the text editor looses its focus. 

Can you please help me on this?

**Comment by Chem-Lab** [comment]
I have the same problem. Only when I don't change the text in the editor.

**Comment by marucjmar** [comment]
Ok, thanks
fix this in version 0.1.7
