### ISSUE TITLE
Editor does not work in modal

### ISSUE THREAD

**Issue by devtoro** [marucjmar/ember-cli-tinymce#14]
I am trying to use the editor in a modal, but it does not seem to work. 

When I click on one of the action of the editor ( undo etc ) I get the following error:

Cannot read property 'nodeType' of undefined.

I am thankful  for any help or lead on this :)

**Comment by marucjmar** [comment]
Hi,

What addon do you use for modal dialog?

**Comment by Chem-Lab** [comment]
I work with ember-paper and it doesn't give an error, but I can't edit the text. I don't see the text.

**Comment by marucjmar** [comment]
Ups, I commit changes to master branch 😞 

@Chem-Lab or @devtoro - Can you check it?
package.json

```
"ember-cli-tinymce": "git@github.com:marucjmar/ember-cli-tinymce.git#master"
```

**Comment by Chem-Lab** [comment]
Yes,

I can confirm that it is working now!
Thanks,
Frank Stock
> Op 5 jul. 2017, om 18:58 heeft Marcin Lazar <notifications@github.com> het volgende geschreven:
> 
> "ember-cli-tinymce": "git@github.com <mailto:git@github.com>:marucjmar/ember-cli-tinymce.git#master"



All our activities are subject to the Chem-Lab nv conditions. Subject to your rejection they will be deemed accepted. A free copy can be foundhereor will be sent to you at your request.

**Comment by marucjmar** [comment]
Thanks
👍 ⭐️ 🎆
