### ISSUE TITLE
How do you import language packs into your plugin

### ISSUE THREAD

**Issue by daniel-lij** [marucjmar/ember-cli-tinymce#19]
I use the component you wrote in ember, and use language in options: 'zh_CN' found that the file was not found, and I hope the author can give me the answer, thanks

**Comment by marucjmar** [comment]
So you can provide the url file in options, and store lang file in public dir.

```
options: {
  language_url: 'langs/zh_cn.js'
  language: 'zh_CN'
}
```
```
{{tinymce-editor options=options value=text}}
```
documentation: https://www.tinymce.com/docs/configure/localization/#language_url
https://www.tinymce.com/docs/get-started/localize-your-language/
