### ISSUE TITLE
Needs option for setting cdn version

### ISSUE THREAD

**Issue by coreypmurphy** [marucjmar/ember-cli-tinymce#4]
Add-on is pointing at specific release of Tinymce via their cdn and is therefor hidden from modification by the app owner/dev.  Would be good to have an addtional option to set in the environment.js besides "load: true", that allows setting the version to fetch from the cdn.  Currently, the add-on is pointing at 4, which isn't a bad thing since it's following semver, except Tinymce released 4.5.0 this past weekend and  caused ordered/unordered list buttons to suddenly disappear from the toolbar.  They've not yet acknowledged this issue but being able to specify a release version in our ember apps would help devs to control add-on updating which we're already accustomed to doing in our package and bower json files.

Pull request #5 submitted.

**Comment by marucjmar** [comment]
Good idea, thanks :+1:
