### ISSUE TITLE
TypeError: Cannot read property of 'cloneNode' of null...

### ISSUE THREAD

**Issue by coreypmurphy** [marucjmar/ember-cli-tinymce#6]
Getting this error when closing the modal containing the tinymce component.  Started getting this error after updating our add on version from 0.0.8 to 0.1.3.

![screen shot 2016-12-08 at 1 18 00 pm](https://cloud.githubusercontent.com/assets/674306/21024145/0937ea5e-bd49-11e6-916e-d5a84d873593.png)

Overall, script error is not impacting performance of running app but is blowing up PhantomJS acceptance tests.

**Comment by marucjmar** [comment]
Set the version of tinyMCE to 4 in ENV

```js
ENV:{
  ...,
  tinyMCE:{
    version: 4 
  }
}
```

whether it solves problem?

**Comment by coreypmurphy** [comment]
No dice.  I have the "version" property set to 4.4.

![screen shot 2016-12-08 at 2 02 50 pm](https://cloud.githubusercontent.com/assets/674306/21025699/0970bedc-bd4f-11e6-8296-3429e54c2745.png)

**Comment by coreypmurphy** [comment]
I've implemented a workaround that allows us to gracefully exit ```setEvents()```if the component is "destroying" an editor instance.  Basically I set a flag just before the ```editor.destroy()``` method is called during ```willDestroy()``` that I use to avoid debouncing the ```contentChanged``` method.

Not sure if there's a more "ember-way" to accomplish this but it prevents the error by not trying to set the value of a destroyed or in-destruction editor instance.  Code below:

```
destroying: false,

setEvents: observer('editor', function() {
    let editor = this.get('editor');
    editor.on('change keyup keydown keypress mousedown', ()=>{
      if(this.get('destroying')){ return; }
      run.debounce(this, this.contentChanged, editor, 1);
    });
  }),

willDestroyElement(){
    let editor = this.get('editor');
    if(editor){
      this.set('destroying',true);
      editor.destroy();
    }
  }
```
If this is acceptable I can submit another PR.

**Comment by coreypmurphy** [comment]
PR #7 submitted.

**Comment by marucjmar** [comment]
Could you check this example is works?
https://gist.github.com/marucjmar/ed55849ba6d0a74b5aa4ac468ac62edd

**Comment by coreypmurphy** [comment]
Doh, pulling off the listeners is way more efficient and "proper" than my solution.  Wasn't thinking with my jquery brain.  Works on my end and my test suites are still happy as well.  Thanks a bunch for this!

**Comment by marucjmar** [comment]
Ok, Thank :smile:  

Fix this problem
